### PR TITLE
Add indncator on navigation

### PR DESCRIPTION
**Pull request by Arkar-Aung**
I just added navigation indicator on current selected page.

### CODE REVIEW

**Comment by greenlikeorange** [comment]
@Arkar-Aung Can you please fix conflicts?

**Comment by Arkar-Aung** [comment]
Ok Wait !! @greenlikeorange Conflict on this pull request is so complex. I just pulled another request. Sorry for my clumsy mistake. I just closed this pull request.

**Comment by greenlikeorange** [comment]
Yep sure

**Comment by greenlikeorange** [comment]
@Arkar-Aung Do you want to join our myanmarfloodinfo's slack? Let me invite you if you want!

**Comment by Arkar-Aung** [comment]
Yep sure !! I want to join and help !!

**Comment by greenlikeorange** [comment]
`darkar1001@gmail.com` can i invite by this email?

**Comment by Arkar-Aung** [comment]
Yep. That's my email.

**Comment by greenlikeorange** [comment]
Invited,please check you email.

**Comment by Arkar-Aung** [comment]
Got it ! Thanks !

**Pull request closed without merging**
